export enum GrupoRiesgo {
  BAJO = 'BAJO',
  MEDIO = 'MEDIO',
  ALTO = 'ALTO',
}

export enum NivelRiesgo {
  VERDE = 'VERDE',
  AMARILLO = 'AMARILLO',
  ROJO = 'ROJO',
}

export enum CausaListaNegra {
  INCUMPLIMIENTO_CONTRATO = 'INCUMPLIMIENTO_CONTRATO',
  COMPORTAMIENTO_INADECUADO = 'COMPORTAMIENTO_INADECUADO',
  DOCUMENTACION_FALSA = 'DOCUMENTACION_FALSA',
  SEGURIDAD_INDUSTRIAL = 'SEGURIDAD_INDUSTRIAL',
  REINCIDENCIA = 'REINCIDENCIA',
  OTRA = 'OTRA',
}
